apiVersion: v1
kind: Service
metadata:
  name: atn
  labels:
    app: atn
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
    nodePort: 31916
  selector:
    app: atn
  type: NodePort
